### ISSUE TITLE
app crash when app is not currently active

### ISSUE THREAD

**Issue by omerfarukz** [Agasper/unity-android-notifications#1]
tried some variations of this plugin. thats perfect. but i got an issue. created a new notification with 10secs delay and closed application(not exit, only pause). after 10 seconds, app crashed. logs are bellow. thanks.

E/AndroidRuntime(10937): Process: com.omr, PID: 10937
E/AndroidRuntime(10937): java.lang.Error: FATAL EXCEPTION [main]
E/AndroidRuntime(10937): Unity version     : 5.0.0f4
E/AndroidRuntime(10937): Device model      : asus Nexus 7
E/AndroidRuntime(10937): Device fingerprint: google/razor/flo:5.1/LMY47O/1783956:user/release-keys
E/AndroidRuntime(10937): 
E/AndroidRuntime(10937): Caused by: java.lang.RuntimeException: Unable to start receiver net.agasper.unitynotification.UnityNotificationManager: java.lang.NullPointerException
E/AndroidRuntime(10937): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2616)
E/AndroidRuntime(10937): 	at android.app.ActivityThread.access$1700(ActivityThread.java:151)
E/AndroidRuntime(10937): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380)
E/AndroidRuntime(10937): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(10937): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(10937): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(10937): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10937): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(10937): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(10937): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime(10937): Caused by: java.lang.NullPointerException
E/AndroidRuntime(10937): 	at java.lang.Class.classForName(Native Method)
E/AndroidRuntime(10937): 	at java.lang.Class.forName(Class.java:309)
E/AndroidRuntime(10937): 	at java.lang.Class.forName(Class.java:273)
E/AndroidRuntime(10937): 	at net.agasper.unitynotification.UnityNotificationManager.onReceive(UnityNotificationManager.java:88)

**Comment by Agasper** [comment]
I can't repeat this problem. Please post your manifest file

**Comment by omerfarukz** [comment]
would you like to share sample project?

**Comment by Agasper** [comment]
Are you just edit timer in sample project and got that ?

**Comment by omerfarukz** [comment]
himm, i think its mine problem. your sample project works correctly. what is my mistake? copied asset folder to my project only. what are the next steps can i do?

**Comment by Agasper** [comment]
Did you edit manifest file ?

**Comment by omerfarukz** [comment]
no, its identical to yours

**Comment by Agasper** [comment]
I didn't test it on Unity 5.x, maybe problem in it
Try to change
private static string unityClass = "com.unity3d.player.UnityPlayerNativeActivity";
to
private static string unityClass = "com.unity3d.player.UnityPlayerActivity";

**Comment by omerfarukz** [comment]
already upgraded your project to untiy 5. its works normally. my project going to crash when suspended or closed.

**Comment by Agasper** [comment]
Send me your project to agasper@yandex.ru, i'll take a look

**Comment by omerfarukz** [comment]
hi agasper, the problem is solved when i call notification method with long typed delay argument. before i am using integer type. its works. thank you

**Comment by omerfarukz** [comment]
removed clear notification code and the problem is solved. i,m not need it. Because notification's not duplicated when i am using same notification id. thank you very much.

**Comment by Agasper** [comment]
you are welcome

**Comment by zulqarnain26** [comment]
Removed clear notification but still getting the same crash
