### ISSUE TITLE
"app has stopped" pushing notif when the app already quit

### ISSUE THREAD

**Issue by Solid-Metal** [Agasper/unity-android-notifications#10]
hey, i got a problem when try launching notif when the app is not active
when i launch the app the notif can come out fine, but not when its off
i use unity 5.2.3 , and the got the exact manifest like yours
i only run the SendRepeatingNotification once on start function with 10 seconds delay

heres the logcat:
--------- beginning of /dev/log/system
W/BroadcastQueue(  478): Unable to launch app bundleIDhere/10183 for broadcast Intent { flg=0x14 cmp=bundleIDhere>/net.agasper.unitynotification.UnityNotificationManager (has extras) }: process is bad
V/AlarmManager(  478): triggered: flg=0x14
V/AlarmManager(  478): Pkg: bundleIDhere
W/BroadcastQueue(  478): Unable to launch app bundleIDhere/10183 for broadcast Intent { flg=0x14 cmp=bundleIDhere>/net.agasper.unitynotification.UnityNotificationManager (has extras) }: process is bad
V/AlarmManager(  478): triggered: flg=0x14
V/AlarmManager(  478): Pkg: bundleIDhere
W/BroadcastQueue(  478): Unable to launch app bundleIDhere/10183 for broadcast Intent { flg=0x14 cmp=bundleIDhere>/net.agasper.unitynotification.UnityNotificationManager (has extras) }: process is bad
V/AlarmManager(  478): triggered: flg=0x14
V/AlarmManager(  478): Pkg: bundleIDhere

how do i fix it?
thank you in advance

**Comment by Solid-Metal** [comment]
on different device, theres no error popup, but the notification didnt show up at all

**Comment by Agasper** [comment]
What's android version do u use ?
Did you try example project on that device ?

**Comment by zory** [comment]
I have same issue.
Crash, when notification tries to show up while app is not running.
I'm using 5.1.1 Android version on LG Nexus 4 phone.

**Comment by Agasper** [comment]
same questions

**Comment by Agasper** [comment]
What's Unity version ?

**Comment by zory** [comment]
Right now I'm using Unity version 5.2.3p1

**Comment by JaroslavL** [comment]
Hi! Thx for great plugin! U mast modify AndroidManifest.xml. I think so

**Comment by Agasper** [comment]
Try new version, and open new issue if doens't fixed

**Comment by TanveerakaRocker** [comment]
Hi Agasper,
I've updated latest plugin, and having issue opening the app from notification, can you help resolve this.
Thanks,
Tanveer
