### ISSUE TITLE
Null Pointer Exception - Crash

### ISSUE THREAD

**Issue by ItsGenN** [Agasper/unity-android-notifications#112]
Caused by: java.lang.NullPointerException: 
 
  at net.agasper.unitynotification.UnityNotificationManager.onReceive (UnityNotificationManager.java:153)
 
  at android.app.ActivityThread.handleReceiver (ActivityThread.java:2725)

I guess this is caused by the following reason:
* When we register for push notifications it also take "Actions" as function parameters, if we use action it will array of action otherwise it will send null which is fine.
* In my case i'm not using any actions when i register for notification it passes null in the parameters of actions, but when it is time to receive the notification it create an array and puts all actions into that array even when actions are null, so there is an exception caused which caused crash.
Kindly fix that issue ASAP. All you can do is to add a check if actions are not null then add it to the array.
Thanks.

**Comment by Agasper** [comment]
There is no support, you can fix it by yourself and make a pull request

**Comment by ItsGenN** [comment]
Can you tell me how can i extract edit files in notification.jar, any software or something.

**Comment by Agasper** [comment]
Open plugin sources in Android Studio, fix it, and build
https://github.com/Agasper/unity-android-notifications/tree/master/PluginSrc
