### ISSUE TITLE
Deprecated?

### ISSUE THREAD

**Issue by CodeMasterYi** [Agasper/unity-android-notifications#130]
Deprecated?

**Comment by mramadhanrh** [comment]
Last commit 2 years ago, and it's just Readme Update 
https://github.com/Agasper/unity-android-notifications/commit/850e1e116d01c06ec3cb2a65f92c428096ab10fe

also, the last script change is in Jan 2019, I think so
https://github.com/Agasper/unity-android-notifications/commits/master

**Comment by Agasper** [comment]
Unity has internal notification system, so there's no point to support this plugin anymore
