### ISSUE TITLE
Text not change?

### ISSUE THREAD

**Issue by cuopbjen0o0** [Agasper/unity-android-notifications#14]
When i put 2 notifications, the second text is always show the text of the first. Can i missing something to remove cache ?

**Comment by Agasper** [comment]
Please provide your code

**Comment by vexe** [comment]
Same here. Running the "NotificationTest" test sample code, no matter what button I click it always shows the  "Title - Long message text" notification (running on a Tablet, Kitkat 4)

**Comment by sunduk** [comment]
I solved this.
Use "PendingIntent.FLAG_UPDATE_CURRENT" option.

am.setRepeating(0, System.currentTimeMillis() + delay, rep, PendingIntent.getBroadcast(currentActivity, id, intent, 0));
->
am.setRepeating(0, System.currentTimeMillis() + delay, rep, PendingIntent.getBroadcast(currentActivity, id, intent, PendingIntent.FLAG_UPDATE_CURRENT));
