### ISSUE TITLE
Use only big icon

### ISSUE THREAD

**Issue by BlueKyle** [Agasper/unity-android-notifications#15]
Is it possible to use only big icon in notification and don't use the small icon?
Or at least make the small icon transparent?

I've tried to remove the small icon parameter, but it make the app not working. And then I tried to give the small icon a transparent image, but there is a background color  around it. I've also tried to change the number in Color32, but the result only change the background color, and not make it transparent.
![screenshot_2016-02-10-16-16-17](https://cloud.githubusercontent.com/assets/7576818/12943124/b73ab954-d011-11e5-8ef5-b4a9af8972d3.png)

Thank you.

**Comment by Agasper** [comment]
No, small icon is required
