### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Mangladar** [Agasper/unity-android-notifications#16]
I'm getting crash in example project. I opened project as it is and added NotificationTest.cs to MainCamera, and the app crashes at time when the notification should appear.

**Comment by Agasper** [comment]
Please provide ADB logs

**Comment by Mangladar** [comment]
Here. I logged it just after the crash, so maybe the interesting part will be at the end.

[log.txt](https://github.com/Agasper/unity-android-notifications/files/126449/log.txt)

**Comment by Agasper** [comment]
I just realized, this plugin doesn't support Android 4.0. Please upgrade your OS if possible

**Comment by Mangladar** [comment]
Thanks for such a quick response!
