### ISSUE TITLE
FATAL EXCEPTION:

### ISSUE THREAD

**Issue by vandelpal** [Agasper/unity-android-notifications#17]
HI. If I change NotificationTest.cs class in your Test progect for this code:
public class NotificationTest : MonoBehaviour {
    void OnApplicationPause(bool paused) {
        if (paused)
            EnableNotifications();
        else
            DisableNotifications();
    }
    void OnApplicationQuit() {
        EnableNotifications();
    }
    void EnableNotifications() {
        LocalNotification.SendNotification(1, 10, "Title", "Long exact message text", new Color32(0xff, 0x44, 0x44, 255), executeMode: LocalNotification.NotificationExecuteMode.ExactAndAllowWhileIdle);
    }
    void DisableNotifications() {
            LocalNotification.CancelNotification(1);
    }
}

Exception in Android logs:
02-12 11:20:01.221: E/AndroidRuntime(3595): FATAL EXCEPTION: main
02-12 11:20:01.221: E/AndroidRuntime(3595): java.lang.Error: FATAL EXCEPTION [main]
02-12 11:20:01.221: E/AndroidRuntime(3595): Unity version     : 5.3.1f1
02-12 11:20:01.221: E/AndroidRuntime(3595): Device model      : samsung GT-P5110
02-12 11:20:01.221: E/AndroidRuntime(3595): Device fingerprint: samsung/espresso10wifixx/espresso10wifi:4.2.2/JDQ39/P5110XXDMI1:user/release-keys
02-12 11:20:01.221: E/AndroidRuntime(3595): Caused by: java.lang.RuntimeException: Unable to start receiver net.agasper.unitynotification.UnityNotificationManager: java.lang.NullPointerException: name == null
02-12 11:20:01.221: E/AndroidRuntime(3595): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2448)
02-12 11:20:01.221: E/AndroidRuntime(3595): 	at android.app.ActivityThread.access$1600(ActivityThread.java:150)
02-12 11:20:01.221: E/AndroidRuntime(3595): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
02-12 11:20:01.221: E/AndroidRuntime(3595): 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-12 11:20:01.221: E/AndroidRuntime(3595): 	at android.os.Looper.loop(Looper.java:175)
02-12 11:20:01.221: E/AndroidRuntime(3595): 	at android.app.ActivityThread.main(ActivityThread.java:5279)
02-12 11:20:01.221: E/AndroidRuntime(3595): 	at java.lang.reflect.Method.invokeNative(Native Method)
02-12 11:20:01.221: E/AndroidRuntime(3595): 	at java.lang.reflect.Method.invoke(Method.java:511)
02-12 11:20:01.221: E/AndroidRuntime(3595): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
02-12 11:20:01.221: E/AndroidRuntime(3595): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
02-12 11:20:01.221: E/AndroidRuntime(3595): 	at dalvik.system.NativeStart.main(Native Method)
02-12 11:20:01.221: E/AndroidRuntime(3595): Caused by: java.lang.NullPointerException: name == null
02-12 11:20:01.221: E/AndroidRuntime(3595): 	at java.lang.Class.classForName(Native Method)
02-12 11:20:01.221: E/AndroidRuntime(3595): 	at java.lang.Class.forName(Class.java:217)
02-12 11:20:01.221: E/AndroidRuntime(3595): 	at java.lang.Class.forName(Class.java:172)
02-12 11:20:01.221: E/AndroidRuntime(3595): 	at net.agasper.unitynotification.UnityNotificationManager.onReceive(UnityNotificationManager.java:95)
02-12 11:20:01.221: E/AndroidRuntime(3595): 	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2441)
02-12 11:20:01.221: E/AndroidRuntime(3595): 	... 10 more

**Comment by Agasper** [comment]
Please read the F.A.Q. Generate a new unique id for every new notification

**Comment by vandelpal** [comment]
You probably did't understand me. I don't create here a few notifications. I create one. But instead of it getting crash. For the test run application and exit. After 10 seconds, instead of the notification get crash. If you delete this line LocalNotification.CancelNotification(1); that all is well.

Ie, can not be called:
LocalNotification.CancelNotification(1);
LocalNotification.SendNotification(1, ...)

May be need check for pending intent is already running before cancel?
Intent checkIntent = new Intent(currentActivity, UnityNotificationManager.class);
alarmUp = (PendingIntent.getBroadcast(currentActivity, id, checkIntent, PendingIntent.FLAG_NO_CREATE) != null);

**Comment by Agasper** [comment]
Comment CancelNotification and try again

**Comment by vandelpal** [comment]
It seems that you don't want understand me, because you don't know how to fix this error. I found a way around this problem. Had to modify the LocalNotification class.
Your plugin there is no way to cancel all notifications. If you store all unique notifications identifiers, and cancel only scheduled notification then cancelAllNotifications method is easy to write and this fatal exception will not occur!

**Comment by Agasper** [comment]
You can write any method what you want, it's open source project
