### ISSUE TITLE
open app when user tap on notification bar?

### ISSUE THREAD

**Issue by minhit1805** [Agasper/unity-android-notifications#2]
hello, i had add your plugin to my project, it's easy to use and awesome!  but when i tap on notification message it's can't open the app?

**Comment by Agasper** [comment]
Hi, check your startup activity in the manifest. It must be **com.unity3d.player.UnityPlayerNativeActivity** also in the code:
```
    private static string fullClassName = "net.agasper.unitynotification.UnityNotificationManager";
    private static string unityClass = "com.unity3d.player.UnityPlayerNativeActivity";
```
