### ISSUE TITLE
CancelAll method not included in unitynotification.jar

### ISSUE THREAD

**Issue by vitordealmeida** [Agasper/unity-android-notifications#23]
Currently provided jar does not include method CancelAll, even though source code does, causing a RuntimeException if it is used. It would be very convenient if you could update the jar so that one would not have to rebuild the project.

**Comment by hippogamesunity** [comment]
Seems that it's not possible to cancel all alarms at low lever API. You have to save all notification ids to PlayerPrefs and use them to cancel notifications.
