### ISSUE TITLE
Notification works only if app is open / minimized

### ISSUE THREAD

**Issue by litemesa** [Agasper/unity-android-notifications#24]
Notification fires if app is open or minimized, if I totally close the app via Application Manger, I don't receive any scheduled notifications, is it correct behavior?

Tested with demo UnityProject on Android 4.4.2

**Comment by Agasper** [comment]
Please provide logs from ADB

**Comment by enriqif** [comment]
I wonder the same thing.. that feature it is configured?

**Comment by dilnur92** [comment]
When I restart my phone, no scheduled notifications are received. I do not know how to resolve that issue as well. Help me, please.

**Comment by Handongji** [comment]
Hello, the same issue,notification works only if app is open or minimized, i can't receive notifications when my app closed. how can i solve it?

**Comment by Ravenh0lm** [comment]
Hi. Same. Notification works only when app is opened or minimized

**Comment by slaczky** [comment]
I had the same problem. Solved it by modifying **LocalNotification.cs line 28** from: `SendNotification(id, (int)delay.TotalSeconds, title, message, Color.white);`
to: `SendNotification(id, (int)delay.Seconds, title, message, Color.white);`

Maybe this solution will work for others too.
My app is designed to show two notifications 24 hours later, after app's first running. It works perfectly!

**Comment by FarshidABZ** [comment]
It doesn't work cause of android 6.0+ battery management, you have to give auto-start permission to your application(game). in my device (asus zenfone 2) I have to set permission in Setting > Battery Management > Auto-start Manager. I can't handle this issue with RECEIVE_BOOT_COMPLETED permission in application. 
Hae any body better idea to handle this ?
