### ISSUE TITLE
how do i make root plugin folder ?

### ISSUE THREAD

**Issue by littlewingsoft** [Agasper/unity-android-notifications#25]
im using many android plugins 
everyplay , and unity purchase etc...

currently plugin path like this =>  Plugins / Android / unitynotification.jar 

but i  want change like this =>   Plugins / Android / localPush / unitynotification.jar 
               
 " localPush " is name of root folder, 

1. make dir   " localPush "
2. move all   andmanifest , jar , res etc..
3. build and run Android Device 
4. F.A.I.L

would you help me?

**Comment by Agasper** [comment]
What kind of FAIL do u have ?

**Comment by littlewingsoft** [comment]
hi agasper

the FAIL is  so simple. not response

not  push notifying message

i guess dont find path jar

**Comment by littlewingsoft** [comment]
this is your unity project

![now](https://cloud.githubusercontent.com/assets/9289173/13950813/7776de40-f070-11e5-99cf-2ec748b0c129.jpg)




this is  i want

![iwant](https://cloud.githubusercontent.com/assets/9289173/13950866/c6c056e8-f070-11e5-96d6-692dea68eb30.jpg)

**Comment by ljackso** [comment]
Hey I had a similar problem, I found that if you place an Android manifest at the top level (directly inside the Android folder) that should solve your issue. If you are considereing having multiple pluggins you will need to have one Android Manifest that covers cover all the perimsions.

You will also need to ensure that in this plugin the variable 'mainActivityClassName' in LocalNotifications.cs, points to the correct name of the main activity in your Manifest File.

**Comment by badrdouah** [comment]
@ljackso could you please explain further this part "You will also need to ensure that in this plugin the variable 'mainActivityClassName' in LocalNotifications.cs, points to the correct name of the main activity in your Manifest File."
