### ISSUE TITLE
APK just vibration without push notification

### ISSUE THREAD

**Issue by parker87tinh** [Agasper/unity-android-notifications#27]
Hello.
Today i tried your Plugin following:
1. i downloaded .zip file and extra my pc. i had 2 folders:PluginSrc and UnityProject
2. i used unity 5.2.2f1 to open UnityProject . everything worked well.
3. i switch to Android and build APK.
4.i installed APK on my android device.
5.i open app and try to push notification. 
==> result: app just vibration my device but didnt push any notification.

do you know why?
Thanks.

**Comment by SectionBoy** [comment]
You need to set the [Status Bar Icons], icon style reference here https://developer.android.com/guide/practices/ui_guidelines/icon_design_status_bar.html

and the icon folder position and icon name reference the authors' files(unity-android-notifications-master\PluginSrc\res\drawable\notify_icon_big.png and notify_icon_small.png).

**Comment by pun777chy** [comment]
Nope the above suggestion doesn't help it at all

**Comment by pun777chy** [comment]
upgrade your project to unity 5.3
