### ISSUE TITLE
Kindle Fire: Local Notifications issue

### ISSUE THREAD

**Issue by dilnur92** [Agasper/unity-android-notifications#29]
When I tried to run this exact application, without any modifications, I am getting a crash when I am receiving local notifications on my Kindle Fire device. I see no issues anywhere, yet I am not able to resolve this issue. Maybe, it got something to with the manifest file. I appreciate any suggestions.

**Comment by SectionBoy** [comment]
If you launch app first time you can't execute CancelNotification(), you need SendNotification() or SendRepeatingNotification() first.

I just fix this problem yesterday. Hope helpful for you.
