### ISSUE TITLE
Notification doesn't launch the app

### ISSUE THREAD

**Issue by SectionBoy** [Agasper/unity-android-notifications#30]
Does anyone know the issue [Notification doesn't launch the app] how to set in AndroidManifest.xml ??

Original description:
Set LocalNotification.mainActivityClassName to the your main activity class (from manifest)

**Comment by SectionBoy** [comment]
I miss understand the description. I need find out the Main Activity Name in AndroimManidest.xml and use this name to replace LocalNotification.mainActivityClassName parameter. Not fix the Main Activity Name become "com.unity3d.player.UnityPlayerNativeActivity".

**Comment by rajeshalluri** [comment]
Hi there, Did you manage to fix this issue.

**Comment by shekharskamble** [comment]
Hi,

Did you managed to resolve? We have the same issue, thanks
