### ISSUE TITLE
Getting white icon in push notification

### ISSUE THREAD

**Issue by csumsky3** [Agasper/unity-android-notifications#35]
Hello,

I'm attempting to only use the small icons, but on one of our devices (Nexus 5), the icon shows up as just white. I have all the small icons in the res/ folder at what I believe are the right sizes (I just used the same sizes you had, and the same sizes listed here http://iconhandbook.co.uk/reference/chart/android/). Have you seen this issue before? Any ideas how to fix it? 

Cheers,
Chris
![notification on device](https://cloud.githubusercontent.com/assets/3428098/17336561/9c51d248-5893-11e6-9e11-5c9d50c6ce45.png)
![unity](https://cloud.githubusercontent.com/assets/3428098/17336562/9d296e7e-5893-11e6-91cb-e03a512e5bee.PNG)

**Comment by JokerDCR** [comment]
android 5.0+ requests all white icon. u can search this in stackoverflow.
