### ISSUE TITLE
Local Notification only vibrates but nothing shown in status bar

### ISSUE THREAD

**Issue by DsD743** [Agasper/unity-android-notifications#36]
Hi Guys! Just found this problem. I've already follow every step from this github. When I try on an empty project, it worked perfectly. Can it do something with another plugin / plugin conflict? or something wrong in manifest? Or are there any reasons? Please help. I'm so desperate. Thank you

Below is my androidmanifest

(can't upload xml file here)

[androidmanifest.txt](https://github.com/Agasper/unity-android-notifications/files/415445/androidmanifest.txt)

**Comment by DsD743** [comment]
I've searched furthure more, and I found some errors. This is the log from adb

I/dalvikvm(15635): Could not find method android.app.AlarmManager.setExactAndAllowWhileIdle, referenced from method net.
agasper.unitynotification.UnityNotificationManager.SetNotification
W/dalvikvm(15635): VFY: unable to resolve virtual method 113: Landroid/app/AlarmManager;.setExactAndAllowWhileIdle (IJLa
ndroid/app/PendingIntent;)

**Comment by Agasper** [comment]
Please check the new version

**Comment by sethisahil271** [comment]
I have the exact issue, were you able to solve it?
