### ISSUE TITLE
Notification doesn't launch the app

### ISSUE THREAD

**Issue by rajeshalluri** [Agasper/unity-android-notifications#37]
Hello Everyone, 

I am using this in Unity game, Notification works fine but the Notification doesn't launch the app, Please help thanks in advace

**Comment by shekharskamble** [comment]
Hi, 

Did you managed to resolve. We have the same issue, thanks

**Comment by evgeny-detkov** [comment]
You may have specified an incorrect name activity.
See LocalNotification.cs -> mainActivityClassName = "you activity from AndroidManifest.xml";
For example:
AndroidManifest.xml

`<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.unity3d.player" android:installLocation="preferExternal" android:theme="@android:style/Theme.NoTitleBar" android:versionCode="1" android:versionName="1.0">
  <supports-screens android:smallScreens="true" android:normalScreens="true" android:largeScreens="true" android:xlargeScreens="true" android:anyDensity="true" />
  <uses-sdk android:minSdkVersion="16" />
  <uses-permission android:name="android.permission.INTERNET" />
  <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
  <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
  <uses-permission android:name="android.permission.VIBRATE" />
  <application android:icon="@drawable/app_icon" android:label="@string/app_name" android:debuggable="true">
    
    <receiver android:name="net.agasper.unitynotification.UnityNotificationManager">
    </receiver>
    
    <activity android:name="com.unity3d.player.UnityPlayerNativeActivity" android:label="@string/app_name">
      <meta-data android:name="unityplayer.UnityActivity" android:value="true" />
      <meta-data android:name="unityplayer.ForwardNativeEventsToDalvik" android:value="true" />
	  <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
      </intent-filter>
    </activity>    
  </application>
</manifest>`

LocalNotification.cs
private static string mainActivityClassName = "**com.unity3d.player.UnityPlayerNativeActivity**";

**Comment by shekharskamble** [comment]
Yes thats the fix... thanks evgeny-detkov
