### ISSUE TITLE
How to include bigPicturestyle in this code ???

### ISSUE THREAD

**Issue by wrooom68** [Agasper/unity-android-notifications#4]
i have tried to edit the provided plugin with android builder.setstyle(new bigpicturestyle) method  but new generated jar does not work. please suggest the best way to do this or provide the plugin with bigpicturestyle ,, please ..

**Comment by Agasper** [comment]
You should put your big image in "UnityProject/Assets/Plugins/Android/res/" and use it filename without extension in bigIcon variable
