### ISSUE TITLE
Obsolete Message

### ISSUE THREAD

**Issue by jfullola1** [Agasper/unity-android-notifications#48]
When I try to call SendNotification function I get the next message :

(LocationNotification is obsolete: LocationNotification is deprecated. Please use iOS.LocalNotification instead (UnityUpgradable) -> UnityEngine.iOS.LocalNotification)

The problem is that I need to use on android device, not iOS.

If I am not wrong, I have to rebuild the plugin, but I'm new on this and I don't know how to do that.
Could anyone help me, please? 
Thanks.

**Comment by UncleJey** [comment]
Use examples
