### ISSUE TITLE
Using NotificationCompat.Builder instead of Notification.Builder

### ISSUE THREAD

**Issue by behzad-mehrtash** [Agasper/unity-android-notifications#49]
Hello!!
I have imported the android project in Android studio and tried building it using Gradle build tool. as a result, I got an Android .AAR file and it worked perfectly with unity. 
Now, I'm trying to use new NotificationCompat.Builder in android code instead of Notification.Builder. but this requires using android-support-v4. this means that I should add a new dependency to gradle.build file to include the android support library inside my .AAR file which I did.
the problem is Gradle does not include the android-support-v4 in .AAR file and I cannot add the android-support-v4.jar to Unity. I would really appreciate any help.

**Comment by Agasper** [comment]
Please check the new version
