### ISSUE TITLE
missing values in onReceive() and "no valid small icon" crash

### ISSUE THREAD

**Issue by janoskovats** [Agasper/unity-android-notifications#51]
use 

PendingIntent.getBroadcast(currentActivity, id, intent, PendingIntent.FLAG_UPDATE_CURRENT)

instead of 

PendingIntent.getBroadcast(currentActivity, id, intent, 0)

see:
https://stackoverflow.com/questions/18649728/android-cannot-pass-intent-extras-though-alarmmanager

**Comment by mjawadamjad** [comment]
I passed Null as small icon and it worked.
