### ISSUE TITLE
Payload to unity with the notification 

### ISSUE THREAD

**Issue by lallutin** [Agasper/unity-android-notifications#54]
could you add payload string to go with the notification 

I could add notification id so i can check it as a payload 

`notificationIntent.putExtra("id",id);`

This will get the data if application starts with the notification

```
AndroidJavaClass unityPlayerClass = new AndroidJavaClass("com.unity3d.player.UnityPlayer");
var activityObject = unityPlayerClass.GetStatic<AndroidJavaObject>("currentActivity");
AndroidJavaObject intent = activityObject.Call<AndroidJavaObject>("getIntent");
intent.Call<int>("getIntExtra", "id",0)
```

But i can't find a way to get this if the application is allready running when the notification is clicked

**Comment by Agasper** [comment]
Fell free to use sources to add any features you want
