### ISSUE TITLE
Ignoring notification Unity 5.0

### ISSUE THREAD

**Issue by RoWaiR** [Agasper/unity-android-notifications#6]
I get this error if you use the plugin in unity 5.0 anyone know how to fix it?

Ignoring notification with icon==0: Notification(pri=0 contentView=net.agasper.notificationtest/0x10900b0 vibrate=null sound=null defaults=0x0 flags=0x10 kind=[null])

**Comment by Agasper** [comment]
Add icon file to the project in directory UnityProject\Assets\Plugins\Android\res\drawable\notify_icon_small.png

as in the example project
