### ISSUE TITLE
Clear Notifications that have triggered

### ISSUE THREAD

**Issue by jhocking** [Agasper/unity-android-notifications#60]
I'm using this plugin to schedule notifications and it's working great for that. However I've noticed that notifications don't clear out when I open the app. I'm not an Android expert so maybe I'm misunderstanding how this all works, but I think AlarmManager.cancel() only affects pending notifications, and clearing triggered notifications is done with NotificationManager.cancel()

I saw this here: https://stackoverflow.com/questions/19268450/how-to-remove-notification-from-notification-bar-programmatically-in-android

And actually what I would really like is a clearNotifications method in the plugin that calls NotificationManager.cancelAll(), since what I mostly want to do is want to clear them all on startup.

Am I correct about all this, and can these be added to the plugin?

**Comment by jhocking** [comment]
I'm tempted to patch this in myself and make a pull request, should I?

**Comment by Agasper** [comment]
Yes, feel free to make a pull request
