### ISSUE TITLE
Unable to convert classes into dex format.

### ISSUE THREAD

**Issue by aliataiyan** [Agasper/unity-android-notifications#62]
CommandInvokationFailure: Unable to convert classes into dex format.
C:/Program Files/Java/jdk1.8.0_144\bin\java.exe -Xmx2048M -Dcom.android.sdkmanager.toolsdir="F:/Softwares/Programming/Android/SDKv24.3.2Full\tools" -Dfile.encoding=UTF8 -jar "E:\Program Files\Unity\Editor\Data\PlaybackEngines\AndroidPlayer/Tools\sdktools.jar" -

stderr[
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lnet/agasper/unitynotification/BuildConfig;
Uncaught translation error: java.lang.IllegalArgumentException: already added: Lnet/agasper/unitynotification/UnityNotificationManager;
2 errors; aborting
]
stdout[
processing archive C:\Users\AliAt\Desktop\unity-android-notifications-master\UnityProject\Temp\StagingArea\android-libraries\support-compat-25.2.0\libs\.\classes.jar...
processing android/support/compat/BuildConfig.class...
processing android/support/v4/accessibilityservice/AccessibilityServiceInfoCompat.class...
processing android/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoIcsImpl.class...
processing android/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoJellyBeanImpl.class...
processing android/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoJellyBeanMr2Impl.class...
processing android/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoStubImpl.class...
processing android/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl.class...
processing android/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs.class...
processing android/support/v4/accessibilityservice/AccessibilityServiceInfoCompatJellyBean.class...
processing android/support/v4/accessibilityservice/AccessibilityServiceInfoCompatJellyBeanMr2.class...
processing android/support/v4/animation/AnimatorCompatHelper.class...
processing android/support/v4/animation/AnimatorListenerCompat.class...
processing android/support/v4/animation/AnimatorProvider.class...
processing android/support/v4/animation/AnimatorUpdateListenerCompat.class...
processing android/support/v4/animation/GingerbreadAnimatorCompatProvider.class...
processing android/support/v4/animation/GingerbreadAnimatorCompatProvider$GingerbreadFloatValueAnimator.class...
processing android/support/v4/animation/GingerbreadAnimatorCompatProvider$GingerbreadFloatValueAnimator$1.class...
processing android/support/v4/animation/HoneycombMr1AnimatorCompatProvider.class...
processing android/support/v4/animation/HoneycombMr1AnimatorCompatProvider$AnimatorListenerCompatWrapper.class...
processing android/support/v4/animation/HoneycombMr1AnimatorCompatProvider$HoneycombValueAnimatorCompat.class...
processing android/support/v4/animation/HoneycombMr1AnimatorCompatProvider$HoneycombValueAnimatorCompat$1.class...
processing android/support/v4/animation/ValueAnimatorCompat.class...
processing android/support/v4/app/ActivityCompat.class...
processing android/support/v4/app/ActivityCompat$1.class...
processing android/support/v4/app/ActivityCompat$OnRequestPermissionsResultCallback.class...
processing android/support/v4/app/ActivityCompat$SharedElementCallback21Impl.class...
processing android/support/v4/app/ActivityCompat$SharedElementCallback23Impl.class...
processing android/support/v4/app/ActivityCompat$SharedElementCallback23Impl$1.class...
processing android/support/v4/app/ActivityCompatApi21.class...
processing android/support/v4/app/ActivityCompatApi21$SharedElementCallback21.class...
processing android/support/v4/app/ActivityCompatApi21$SharedElementCallbackImpl.class...
processing android/support/v4/app/ActivityCompatApi22.class...
processing android/support/v4/app/ActivityCompatApi23.class...
processing android/support/v4/app/ActivityCompatApi23$OnSharedElementsReadyListenerBridge.class...
processing android/support/v4/app/ActivityCompatApi23$RequestPermissionsRequestCodeValidator.class...
processing android/support/v4/app/ActivityCompatApi23$SharedElementCallback23.class...
processing android/support/v4/app/ActivityCompatApi23$SharedElementCallbackImpl.class...
processing android/support/v4/app/ActivityCompatApi23$SharedElementCallbackImpl$1.class...
processing android/support/v4/app/ActivityCompatHoneycomb.class...
processing android/support/v4/app/ActivityCompatJB.class...
processing android/support/v4/app/ActivityManagerCompat.class...
processing android/support/v4/app/ActivityManagerCompatKitKat.class...
processing android/support/v4/app/ActivityOptionsCompat.class...
processing android/support/v4/app/ActivityOptionsCompat$ActivityOptionsImpl21.class...
processing android/support/v4/app/ActivityOptionsCompat$ActivityOptionsImpl23.class...
processing android/support/v4/app/ActivityOptionsCompat$ActivityOptionsImpl24.class...
processing android/support/v4/app/ActivityOptionsCompat$ActivityOptionsImplJB.class...
processing android/support/v4/app/ActivityOptionsCompat21.class...
processing android/support/v4/app/ActivityOptionsCompat23.class...
processing android/support/v4/app/ActivityOptionsCompat24.class...
processing android/support/v4/app/ActivityOptionsCompatJB.class...
processing android/support/v4/app/AppOpsManagerCompat.class...
processing android/support/v4/app/AppOpsManagerCompat$AppOpsManager23.class...
processing android/support/v4/app/AppOpsManagerCompat$AppOpsManagerImpl.class...
processing android/support/v4/app/AppOpsManagerCompat23.class...
processing android/support/v4/app/BundleCompat.class...
processing android/support/v4/app/BundleCompatGingerbread.class...
processing android/support/v4/app/BundleCompatJellybeanMR2.class...
processing android/support/v4/app/BundleUtil.class...
processing android/support/v4/app/INotificationSideChannel.class...
processing android/support/v4/app/INotificationSideChannel$Stub.class...
processing android/support/v4/app/INotificationSideChannel$Stub$Proxy.class...
processing android/support/v4/app/NotificationBuilderWithActions.class...
processing android/support/v4/app/NotificationBuilderWithBuilderAccessor.class...
processing android/support/v4/app/NotificationCompat.class...
processing android/support/v4/app/NotificationCompat$Action.class...
processing android/support/v4/app/NotificationCompat$Action$1.class...
processing android/support/v4/app/NotificationCompat$Action$Builder.class...
processing android/support/v4/app/NotificationCompat$Action$Extender.class...
processing android/support/v4/app/NotificationCompat$Action$WearableExtender.class...
processing android/support/v4/app/NotificationCompat$BigPictureStyle.class...
processing android/support/v4/app/NotificationCompat$BigTextStyle.class...
processing android/support/v4/app/NotificationCompat$Builder.class...
processing android/support/v4/app/NotificationCompat$BuilderExtender.class...
processing android/support/v4/app/NotificationCompat$CarExtender.class...
processing android/support/v4/app/NotificationCompat$CarExtender$UnreadConversation.class...
processing android/support/v4/app/NotificationCompat$CarExtender$UnreadConversation$1.class...
processing android/support/v4/app/NotificationCompat$CarExtender$UnreadConversation$Builder.class...
processing android/support/v4/app/NotificationCompat$Extender.class...
processing android/support/v4/app/NotificationCompat$InboxStyle.class...
processing android/support/v4/app/NotificationCompat$MessagingStyle.class...
processing android/support/v4/app/NotificationCompat$MessagingStyle$Message.class...
processing android/support/v4/app/NotificationCompat$NotificationCompatImpl.class...
processing android/support/v4/app/NotificationCompat$NotificationCompatImplApi20.class...
processing android/support/v4/app/NotificationCompat$NotificationCompatImplApi21.class...
processing android/support/v4/app/NotificationCompat$NotificationCompatImplApi24.class...
processing android/support/v4/app/NotificationCompat$NotificationCompatImplBase.class...
processing android/support/v4/app/NotificationCompat$NotificationCompatImplHoneycomb.class...
processing android/support/v4/app/NotificationCompat$NotificationCompatImplIceCreamSandwich.class...
processing android/support/v4/app/NotificationCompat$NotificationCompatImplJellybean.class...
processing android/support/v4/app/NotificationCompat$NotificationCompatImplKitKat.class...
processing android/support/v4/app/NotificationCompat$Style.class...
processing android/support/v4/app/NotificationCompat$WearableExtender.class...
processing android/support/v4/app/NotificationCompatApi20.class...
processing android/support/v4/app/NotificationCompatApi20$Builder.class...
processing android/support/v4/app/NotificationCompatApi21.class...
processing android/support/v4/app/NotificationCompatApi21$Builder.class...
processing android/support/v4/app/NotificationCompatApi23.class...
processing android/support/v4/app/NotificationCompatApi24.class...
processing android/support/v4/app/NotificationCompatApi24$Builder.class...
processing android/support/v4/app/NotificationCompatBase.class...
processing android/support/v4/app/NotificationCompatBase$Action.class...
processing android/support/v4/app/NotificationCompatBase$Action$Factory.class...
processing android/support/v4/app/NotificationCompatBase$UnreadConversation.class...
processing android/support/v4/app/NotificationCompatBase$UnreadConversation$Factory.class...
processing android/support/v4/app/NotificationCompatExtras.class...
processing android/support/v4/app/NotificationCompatHoneycomb.class...
processing android/support/v4/app/NotificationCompatIceCreamSandwich.class...
processing android/support/v4/app/NotificationCompatIceCreamSandwich$Builder.class...
processing android/support/v4/app/NotificationCompatJellybean.class...
processing android/support/v4/app/NotificationCompatJellybean$Builder.class...
processing android/support/v4/app/NotificationCompatKitKat.class...
processing android/support/v4/app/NotificationCompatKitKat$Builder.class...
processing android/support/v4/app/NotificationCompatSideChannelService.class...
processing android/support/v4/app/NotificationCompatSideChannelService$NotificationSideChannelStub.class...
processing android/support/v4/app/NotificationManagerCompat.class...
processing android/support/v4/app/NotificationManagerCompat$CancelTask.class...
processing android/support/v4/app/NotificationManagerCompat$Impl.class...
processing android/support/v4/app/NotificationManagerCompat$ImplApi24.class...
processing android/support/v4/app/NotificationManagerCompat$ImplBase.class...
processing android/support/v4/app/NotificationManagerCompat$ImplIceCreamSandwich.class...
processing android/support/v4/app/NotificationManagerCompat$ImplKitKat.class...
processing android/support/v4/app/NotificationManagerCompat$NotifyTask.class...
processing android/support/v4/app/NotificationManagerCompat$ServiceConnectedEvent.class...
processing android/support/v4/app/NotificationManagerCompat$SideChannelManager.class...
processing android/support/v4/app/NotificationManagerCompat$SideChannelManager$ListenerRecord.class...
processing android/support/v4/app/NotificationManagerCompat$Task.class...
processing android/support/v4/app/NotificationManagerCompatApi24.class...
processing android/support/v4/app/NotificationManagerCompatIceCreamSandwich.class...
processing android/support/v4/app/NotificationManagerCompatKitKat.class...
processing android/support/v4/app/RemoteInput.class...
processing android/support/v4/app/RemoteInput$1.class...
processing android/support/v4/app/RemoteInput$Builder.class...
processing android/support/v4/app/RemoteInput$Impl.class...
processing android/support/v4/app/RemoteInput$ImplApi20.class...
processing android/support/v4/app/RemoteInput$ImplBase.class...
processing android/support/v4/app/RemoteInput$ImplJellybean.class...
processing android/support/v4/app/RemoteInputCompatApi20.class...
processing android/support/v4/app/RemoteInputCompatBase.class...
processing android/support/v4/app/RemoteInputCompatBase$RemoteInput.class...
processing android/support/v4/app/RemoteInputCompatBase$RemoteInput$Factory.class...
processing android/support/v4/app/RemoteInputCompatJellybean.class...
processing android/support/v4/app/ServiceCompat.class...
processing android/support/v4/app/ServiceCompat$Api24ServiceCompatImpl.class...
processing android/support/v4/app/ServiceCompat$BaseServiceCompatImpl.class...
processing android/support/v4/app/ServiceCompat$ServiceCompatImpl.class...
processing android/support/v4/app/ServiceCompat$StopForegroundFlags.class...
processing android/support/v4/app/ServiceCompatApi24.class...
processing android/support/v4/app/ShareCompat.class...
processing android/support/v4/app/ShareCompat$IntentBuilder.class...
processing android/support/v4/app/ShareCompat$IntentReader.class...
processing android/support/v4/app/ShareCompat$ShareCompatImpl.class...
processing android/support/v4/app/ShareCompat$ShareCompatImplBase.class...
processing android/support/v4/app/ShareCompat$ShareCompatImplICS.class...
processing android/support/v4/app/ShareCompat$ShareCompatImplJB.class...
processing android/support/v4/app/ShareCompatICS.class...
processing android/support/v4/app/ShareCompatJB.class...
processing android/support/v4/app/SharedElementCallback.class...
processing android/support/v4/app/SharedElementCallback$OnSharedElementsReadyListener.class...
processing android/support/v4/app/SupportActivity.class...
processing android/support/v4/app/SupportActivity$ExtraData.class...
processing android/support/v4/content/ContentResolverCompat.class...
processing android/support/v4/content/ContentResolverCompat$ContentResolverCompatImpl.class...
processing android/support/v4/content/ContentResolverCompat$ContentResolverCompatImplBase.class...
processing android/support/v4/content/ContentResolverCompat$ContentResolverCompatImplJB.class...
processing android/support/v4/content/ContentResolverCompatJellybean.class...
processing android/support/v4/content/ContextCompat.class...
processing android/support/v4/content/ContextCompatApi21.class...
processing android/support/v4/content/ContextCompatApi23.class...
processing android/support/v4/content/ContextCompatApi24.class...
processing android/support/v4/content/ContextCompatHoneycomb.class...
processing android/support/v4/content/ContextCompatJellybean.class...
processing android/support/v4/content/ContextCompatKitKat.class...
processing android/support/v4/content/ExecutorCompatHoneycomb.class...
processing android/support/v4/content/IntentCompat.class...
processing android/support/v4/content/IntentCompat$IntentCompatImpl.class...
processing android/support/v4/content/IntentCompat$IntentCompatImplBase.class...
processing android/support/v4/content/IntentCompat$IntentCompatImplHC.class...
processing android/support/v4/content/IntentCompat$IntentCompatImplIcsMr1.class...
processing android/support/v4/content/IntentCompatHoneycomb.class...
processing android/support/v4/content/IntentCompatIcsMr1.class...
processing android/support/v4/content/ModernAsyncTask.class...
processing android/support/v4/content/ModernAsyncTask$1.class...
processing android/support/v4/content/ModernAsyncTask$2.class...
processing android/support/v4/content/ModernAsyncTask$3.class...
processing android/support/v4/content/ModernAsyncTask$4.class...
processing android/support/v4/content/ModernAsyncTask$AsyncTaskResult.class...
processing android/support/v4/content/ModernAsyncTask$InternalHandler.class...
processing android/support/v4/content/ModernAsyncTask$Status.class...
processing android/support/v4/content/ModernAsyncTask$WorkerRunnable.class...
processing android/support/v4/content/ParallelExecutorCompat.class...
processing android/support/v4/content/SharedPreferencesCompat.class...
processing android/support/v4/content/SharedPreferencesCompat$EditorCompat.class...
processing android/support/v4/content/SharedPreferencesCompat$EditorCompat$Helper.class...
processing android/support/v4/content/pm/ActivityInfoCompat.class...
processing android/support/v4/content/res/ConfigurationHelper.class...
processing android/support/v4/content/res/ConfigurationHelper$ConfigurationHelperImpl.class...
processing android/support/v4/content/res/ConfigurationHelper$GingerbreadImpl.class...
processing android/suppor<message truncated>

**Comment by Agasper** [comment]
Check your plugins directory, looks like you put plugin several times
