### ISSUE TITLE
android Java Exception : java.lang.ClassNotFoundException:net.agaspar.unitynotification.UnityNotificationManager

### ISSUE THREAD

**Issue by badrdouah** [Agasper/unity-android-notifications#64]
hello, 
i'm trying to implement your plugin in my project and got this issue , can you please help , 
i'm not really sure about how to install it , i have copied all the files in plugin android folder to the plugin android folder of my project ,i faced an issue which was having another android manifest so i tried to merge the two i have added this line to the original manifest
`        <receiver android:name="net.agasper.unitynotification.UnityNotificationManager"></receiver>`
it compiles but i get this error when i'm on an android device 
can you please help 
thank you

**Comment by meerfolk** [comment]
I've got something like that, my app crash on android 4.2.2. I fix that crashes by adding
 `<uses-permission android:name="android.permission.VIBRATE"/>` 
in AndroidManifest.xml.
