### ISSUE TITLE
`UnityEngine.Application' does not contain a definition for `bundleIdentifier'

### ISSUE THREAD

**Issue by hassan4202** [Agasper/unity-android-notifications#68]
I am using Unity for Android development. When I play the Game on unity console it doesn't give any error but when i Build and run it on android it immediately gives this error Application.bundleIdentifier is giving error no definition is provided for it.
Kindly help me.

**Comment by Agasper** [comment]
https://unity3d.com/ru/unity/beta/unity5.6.0b6

Build Pipeline: Changed 'Application.bundleIdentifier' to 'Application.identifier' and 'PlayerSettings.bundleIdentifier' to 'PlayerSettings.applicationIdentifier'.

**Comment by hassan4202** [comment]
Thank you sir

**Comment by mahdiabiyar** [comment]
thanks

**Comment by Manick94** [comment]
Dude! you deserves a ton of thanks !

**Comment by 8bitcodeblue** [comment]
Hey bro Thanks! @Agasper

**Comment by cherucole** [comment]
> https://unity3d.com/ru/unity/beta/unity5.6.0b6
> 
> Build Pipeline: Changed 'Application.bundleIdentifier' to 'Application.identifier' and 'PlayerSettings.bundleIdentifier' to 'PlayerSettings.applicationIdentifier'.

This worked for me. Thanks!!
