### ISSUE TITLE
Merging with Firebase for push notification causes Error

### ISSUE THREAD

**Issue by SaRaavan** [Agasper/unity-android-notifications#84]
Hi,

       This is not an issue actually, I want to merge this local notification with push notification (Firebase/OneSignal) project. While building the project i'm getting errors, which i tried to fixed for while and couldn't got any solutions. 
Help out to fix those issues.

[Error.txt](https://github.com/Agasper/unity-android-notifications/files/1744136/Error.txt)

**Comment by Agasper** [comment]
Looks like you have problems with NDK and libraries
