### ISSUE TITLE
how to get Notification click callback

### ISSUE THREAD

**Issue by sunxinzhe2012** [Agasper/unity-android-notifications#85]
tks u,good job,but i want to know how to get notification click callback with notification id,like action identifier,this feature is very important in game, the action must click action button to identify,tks very much!

**Comment by sunxinzhe2012** [comment]
@Agasper

**Comment by PinguN00t** [comment]
Same problem : even on the Test scene, I can configure multiple buttons on the notification (which is super cool !) but the buttons don't do anything when I click on them. No log, no app opening (with the app on the background or not)

**Comment by Agasper** [comment]
Unfortunately this feature was added by contributing member, i don't use it, so i can not tell you what's wrong
