### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by LloydCorfex** [Agasper/unity-android-notifications#88]
Does this project need ALL these plugins or can you shrink it to only the necessary?

(Cause there are many many duplicates if using other plugins too)

**Comment by Agasper** [comment]
Just use Google Play resolver to fix that issue

**Comment by LloydCorfex** [comment]
I found out what the problem was / is... and the Resolver is no help -.-'

The Resolver adds v25.2 files to my project.
You use 26.1.
= conflict

I also tried to disable the resolver and just overwrite the 25.2 files.
Result: Can't build

**Comment by Agasper** [comment]
Then you should update your plugins to the newest version, to use latest build-tools

**Comment by Andorfy** [comment]
Hi,

I was the same problem. 
After updating the Firebase Analytics plugin to 4.5.2 and the Google AdMob plugin to 3.13.1 the Play Services Resolver automatically updated the V25.2 plugins to V26.1.0.
