### ISSUE TITLE
App crashes on notification appearance

### ISSUE THREAD

**Issue by Samuraisa** [Agasper/unity-android-notifications#90]
Then notification is triggered, the app is crashing to desktop no matter it is active/fullscreen or it is in background. Tested with Lenovo A850+ (Android 4.2) and Samsung Galaxy S8 (Android 7.0) using Unity 2017.3.1f1 (just reimporting your project no other modifications).

**Comment by sam-mckay** [comment]
I'm having a similar issue with Unity 2017.2.0p1, "AppName has stopped" appears if you schedule a notification and then hard close the app
Backgrounding the app seems to work fine for me

**Comment by sam-mckay** [comment]
@Samuraisa 
If you're still having problems, I managed to get rid of this issue by simply recompiling the android studio plugin... possibly an issue with the build tools version used to create the plugin in the first place

**Comment by Agasper** [comment]
Please provide ADB logs and recreate the issue
